src/crypto.c

In their continued wisdom OpenSSL developers keep breaking APIs left and
right with very poor documentation and forward/backward source compatibility.
Closes #96

Add compatibility with OpenSSL 1.1.0

---

README
src/environ.c
src/mod_auth_gssapi.c
src/mod_auth_gssapi.h
tests/httpd.conf
tests/magtests.py

This option is useful to select and allow only a specific credential
when keys for multiple principals are available in a keytab.

Add option to select acceptor name

---

src/environ.c

The old escaping code only escapes '\"' characters, but RFC4627 also mentions other characters that must be escaped, such as '\n', '/', '\b', etc.
The new code adds support for escaping these characters, and provides a simplified implementation. In particular, instead of iterating the original string twice (one for counting characters, and the other to replace them), only a single iteration is performed always. Memory is allocated as the worst case scenario (i.e. all the characters are to be escaped).
I have used:
```
case '"':  memcpy(p, "\\\"", 2); p += 2; break;
```
because I thougth it was clearer than:
```
case '"': *(p++) = '\\'; *(p++) = '"'; break;
```
But we can change that if you prefer.

Refactor and complete JSON string escape function

---

src/mod_auth_gssapi.c
tests/httpd.conf
tests/magtests.py
tests/t_nonego.py

If the admin sets the gssapi-no-negotiate requets enironemnt variable,
then we suppress the ability to send Negotiate headers.
This is useful to slectively send negotiate only to specific whielisted
or blacklisted browsers, clients, IP Addresses, etc... based on
directives like BrowserMatch or SetEnvIf.
Signed-off-by: Simo Sorce <simo@redhat.com>
Resolves #135

Allow admins to selectively suppress negotiation

---

.travis.sh
.travis.yml
tests/magtests.py
tests/t_bad_acceptor_name.py
tests/t_basic_k5.py
tests/t_basic_k5_fail_second.py
tests/t_basic_k5_two_users.py
tests/t_basic_proxy.py
tests/t_hostname_acceptor.py
tests/t_nonego.py
tests/t_required_name_attr.py
tests/t_spnego.py
tests/t_spnego_negotiate_once.py
tests/t_spnego_no_auth.py
tests/t_spnego_proxy.py
tests/t_spnego_rewrite.py

Currently we test Fedora (rawhide) and Debian (unstable).  Centos7 is not tested because we can't currently build there.  Both clang and gcc builds are run with -Werror.

Add travis support

---

.travis.sh
tests/httpd.conf
tests/magtests.py

- Ensure magtests.py reports failures
- Fix the issue with starting apache in containers
- Update the package lists to run the pkinit test
- Stop repeatedly re-opening the test log file during tests
- Various code cleanliness fixes

Test suite cleanup

---

README

We use some functions that were added only in v 2.4.11, make that the
minimum required version in the docs.
Resloves: #167

Update minimum Apache HTTPD version required

---

src/environ.c
src/mod_auth_gssapi.h
src/util.c

The check to match a mapped name to a named attribute inadvertently
considered only the length of one of the strings.
This would cause incorrect prefix matches.
Fixes #173

Fix truncation on comparison in name attr maps

---

configure.ac

Should address #172.
- Check that the discovered YACC and LEX are available via the PATH and error if not.
- Check that `pkg-config` is available via the PATH and emit a nicer error than the 'unexpected token \'OPENSSL`' we get now.

Add configure errors for missing bison, flex, and pkg-config

---

README

Clarify that this is really only for NTLMSSP, and recommend that it be
left in the off position.

Make description of GssapiConnectionBound scarier

---

.travis.sh
.travis.yml
configure.ac
src/mod_auth_gssapi.h

Apache added ap_log_rdata() in 2.4.11.  However, el7 only has apache
2.4.6, and it's not worth bumping our version requirement for just a
logging function.
Fixes: #184

Allow building without ap_log_rdata()

---

configure.ac
src/crypto.c

Instead of trying to guess which version introduced new openssl
unctions we depend on, detect them in configure and declare them
only if they are not found.
This will fix #188 in a better way than playing with version numbers, hopefully

Detect libcrypto function instead of using version

---

src/mod_auth_gssapi.h

ap_set_flag_slot() requires a field of type `int`.  Previously we
passed type `bool` in two places, causing test failures on s390x
because logging was not correctly configured.

Fix integer sizes used with ap_set_flag_slot()

---

.travis.sh
.travis.yml
tests/magtests.py

Fix test suite to work again with virtualenvs

---

src/mod_auth_gssapi.c

For some reason, passing the mechanism as a parameter to gss_localname does not work with, at least, mech_eap (aka Moonshot).
```
GSS ERROR gss_localname() failed: [The operation or option is not available or unsupported (Name has no attributes)],
```
However, the name does have attributes. 
The gss-server.c example application (https://github.com/krb5/krb5/blob/master/src/appl/gss-sample/gss-server.c#L907) uses GSS_C_NO_OID, and using that value it works.
I've seen MIT KRB's mechglue seems to use the mechanism associated to the name if GSS_C_NO_OID. I wonder whether mechglue is associating mech_eap attributes to a wrong mechanism.

Allow gss_localname to work with at least mech_eap

---

.gitignore
src/mod_auth_gssapi.c

Currently on Basic Auth mag_complete was basically always being called with an empty mech_type.
This will allow in future to consistently query via mech_type for both Negotiate and Basic Auth paths.

Properly handle mech_type for basic auth

---

.travis.sh
README
contrib/sweeper.py

Adapt and document sweeper.py for gssproxy

---

README

Prior to this change, we documented the default values for some of the boolean configuration options, but not all of the options.
Document the default values for all the remaining boolean config options.

README: document default boolean config values

---

README

It's easy for users to accidentally set GssapiSSLonly to "Off" in production, or instruct other users to turn this "Off" without understanding the consequences.
Advise users that they should always use HTTPS in production.

README: add warning for GssapiSSLonly

---

.travis.sh
src/mod_auth_gssapi.c
tests/httpd.conf
tests/localname.html
tests/magtests.py
tests/t_localname.py

Commit 9c555e2a42653153c0f0159446b90a26c14e9465 regressed this interface.
This PR fixes it and adds a test to make sure it stays fixed.
We have to use curl because apparently request_gssapi is not always doing that.

Fix gss_localname

---

README
src/mod_auth_gssapi.c
src/mod_auth_gssapi.h
tests/Makefile.am
tests/httpd.conf
tests/magtests.py
tests/t_bad_acceptor_name.py
tests/t_basic_k5.py
tests/t_basic_k5_fail_second.py
tests/t_basic_k5_two_users.py
tests/t_basic_proxy.py
tests/t_basic_timeout.py
tests/t_localname.py
tests/t_nonego.py
tests/t_required_name_attr.py
tests/t_spnego_negotiate_once.py
tests/t_spnego_no_auth.py
tests/t_spnego_proxy.py
tests/t_spnego_rewrite.py

Add option to control timeout for Basic Auth

---

.gitignore
README
src/environ.c
src/environ.h
src/mod_auth_gssapi.c
src/mod_auth_gssapi.h
tests/Makefile.am
tests/httpd.conf
tests/magtests.py
tests/mech.html
tests/t_mech_name.py

A new option named GssapiPublishMech enables setting an environemnt
variable named GSS_MECH that exposes the authentication type and
mechanism used for authentication.
Fixes #199

Add ability to expose the used mechanism

---

ci/ci.sh
tests/magtests.py

Fixes: https://github.com/gssapi/mod_auth_gssapi/issues/224

tests: Catch errors during tests setup

---

ci/ci.sh
tests/magtests.py

This changes the way in which a test environment is prepared.
Before:
specific -> global
After:
global -> specific
In particular, this allows setting PATH env variable differed from
the global configuration.
Fixes: https://github.com/gssapi/mod_auth_gssapi/issues/226

tests: Don't override the specific environment by the global one

---

src/mod_auth_gssapi.c
tests/httpd.conf
tests/magtests.py
tests/t_file_check.py

This will give a useful warning to admins when config point to missing
files.
Fixes #228

Emit error in logs if keytab files can't be opened

---

README
contrib/session_generator.py
contrib/sweeper.py
tests/magtests.py
tests/t_bad_acceptor_name.py
tests/t_basic_k5.py
tests/t_basic_k5_fail_second.py
tests/t_basic_k5_two_users.py
tests/t_basic_proxy.py
tests/t_basic_timeout.py
tests/t_file_check.py
tests/t_hostname_acceptor.py
tests/t_localname.py
tests/t_mech_name.py
tests/t_nonego.py
tests/t_required_name_attr.py
tests/t_spnego.py
tests/t_spnego_negotiate_once.py
tests/t_spnego_no_auth.py
tests/t_spnego_proxy.py
tests/t_spnego_rewrite.py

When moving 2 -> 3, python elected to keep "python" as the name of the
python2 interpreter.  As a result, python3-only machines have no
/usr/bin/python.  Since python2 is EOL, it should be safe to make our
scripting default to python3.

Move to python3 by default

---

src/parser.y

Bison complains that, for yacc compliance, %type is for nonterminals.
Resolves: #236

Fix type/token distinction in parser.y

---

src/mod_auth_gssapi.c
tests/httpd.conf
tests/magtests.py
tests/t_hostname_acceptor.py

Quoting part of a commit message in this PR: 
When using the {HOTNAME} acceptor the principal used in the server
ccache can vary with each request. GSSAPI does not handle gracefully
a request to resolve a ccache if there is already another credential
under a different name.
Fixes #234

Special ccache handling for {HOSTNAME} acceptor

---

ci/ci.sh
src/crypto.c

OpenSSL 3 changes the padding behavior of EVP_DecryptFinal_ex(), which
causes our decryption to fail.  It is the opnion of the OpenSSL
developers that mod_auth_gssapi's use of this function was incorrect.
Patch suggested by Tomáš Mráz.
Related: https://github.com/openssl/openssl/issues/16351

crypto: Handle EVP changes in OpenSSL 3

---

ci/ci.sh
src/mod_auth_gssapi.c

If no cred store options are present at all the code now crashes trying
to access the structure that should hold the options as it is NULL.
Also add ifdefs that were missed in the original patch.
Fixes #271

Fix a crash bug when s4u2proxy is configured

---

tests/Makefile.am

The file tests/t_file_check.py is missing from the tar because it's not listed in tests/Makefile.am in the EXTRA_DIST variable.
Add the test file.
Fixes: https://github.com/gssapi/mod_auth_gssapi/issues/309

Package tests/t_file_check.py

---

src/asn1c/ber_tlv_length.c

Minor comment fix in ber_skip_length()

minor comment fix ber_skip_length()
